Submitted by: Rehnuma Shabnam Ananya, Nasim Uddin Ahmed

In [0]:
import tensorflow as tf
import numpy as np
import heapq, torch
import matplotlib.pyplot as plt
from tensorflow import keras  
from tensorflow.keras import layers, datasets, models

In [0]:
x = np.array([[5,10,15,30,25],
              [20,30,65,70,90],
              [7,80,95,20,30]])
print(x)
y=tf.nn.top_k(x, 1)
print(y)

[[ 5 10 15 30 25]
 [20 30 65 70 90]
 [ 7 80 95 20 30]]
TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=int64, numpy=
array([[30],
       [90],
       [95]])>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[3],
       [4],
       [2]], dtype=int32)>)


In [0]:
argmax = tf.cast(tf.argmax(x, axis=1), tf.int32)
print(argmax)
#kth = tf.reduce_min(y.values)
#top2 = tf.greater_equal(x, 95)
c= tf.zeros([3,5])
indices_1 = [[0,3]]
indices_2 = [[1,4]]
indices_3 = [[2,2]]

values = [1.0] 
shape = [3, 5]  

delta_1 = tf.SparseTensor(indices_1, values, shape)
result_1 = c + tf.sparse.to_dense(delta_1)
delta_2 = tf.SparseTensor(indices_2, values, shape)
result_2 = c + tf.sparse.to_dense(delta_2)
delta_3 = tf.SparseTensor(indices_3, values, shape)
result_3 = c + tf.sparse.to_dense(delta_3)
result=tf.math.add(result_1, result_2)
result=tf.math.add(result, result_3)
print(result)

tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor(
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


In [0]:
x_shape = tf.shape(x)
k = 3

top_values, top_indices = tf.nn.top_k(tf.reshape(x, (-1,)), k)
top_indices = tf.stack(((top_indices // x_shape[1]), (top_indices % x_shape[1])), -1)
indices = tf.constant([[3], [9], [12]])
updates = tf.constant([30, 90, 95])
shape = tf.constant([15])
scatter = tf.scatter_nd(indices, updates, shape)
print(scatter)

tf.Tensor([ 0  0  0 30  0  0  0  0  0 90  0  0 95  0  0], shape=(15,), dtype=int32)


In [0]:
X=tf.constant([1,2])
ev=tf.constant([2,2])
y=tf.constant([4,5])
z=tf.constant([7,6])
b=tf.constant([0,0])
r=tf.math.floormod(X,ev)
q=tf.math.equal(r,b)
g=tf.math.not_equal(r,b)
indices_eq = tf.where(q)
indices_neq = tf.where(g)
#indices_eq = tf.print(indices_eq, [indices_eq])
print(indices_eq)
print(indices_neq)

#y[0,indices_eq]
#def f1(): return tf.constant(y) #add i, j etc
#def f2(): return tf.constant(z)
#def f3(): return tf.constant(-1)
#p = tf.case([(tf.equal(r, b), f1), (tf.not_equal(r,b), f2)],
  #       default=f3, exclusive=True)
#print(p)

tf.Tensor([[1]], shape=(1, 1), dtype=int64)
tf.Tensor([[0]], shape=(1, 1), dtype=int64)


In [0]:
res_1 = tf.slice(y, [1],  [1])
res_1=tf.dtypes.cast(res_1, tf.float32)
res_2 = tf.slice(z, [0],  [1])
res_2=tf.dtypes.cast(res_2, tf.float32)
c= tf.ones([1,2])
indices_eq=[[0,1]]
indices_neq=[[0,0]]
shape = [1,2]
values=res_1
delta_1 = tf.SparseTensor(indices_eq, values, shape)
result_1 =c * tf.sparse.to_dense(delta_1)
values=res_2
delta_2 = tf.SparseTensor(indices_neq, values, shape)
result_2 =result_1 + tf.sparse.to_dense(delta_2)
print(result_2)

tf.Tensor([[7. 5.]], shape=(1, 2), dtype=float32)


In [112]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]], [[5, 5, 5], [6, 6, 6]]])
l=tf.size(t)
tf.print(l)
h=tf.less(l,100)
f=tf.greater(1,44)
def f1(): return tf.constant(100)
def f2(): return tf.constant(12)
def f3(): return tf.constant(0)
p = tf.case([(tf.greater(l, 100), f1), (tf.logical_or(h,f),f2)],
         default=f3, exclusive=True)
print(p)
#s=tf.data.experimental.Counter(
    #start=0, step=1, dtype=tf.dtypes.int64)
#result = sess.run(p)
#global_step = tf.Variable(1, name='global_step', trainable=False, dtype=tf.int32)
#increment_global_step_op = tf.compat.v1.assign(global_step, global_step+1)
#sess = tf.compat.v1.Session()
#step = sess.run(increment_global_step_op)

18
tf.Tensor(12, shape=(), dtype=int32)
<_ScanDataset shapes: (), types: tf.int64>


In [261]:
t = tf.constant([1, 2, 3, 4])
w = tf.constant([4, 5, 6, 7])
print(w.get_shape())
w = tf.reverse(w, [0], name=None)
t = tf.math.subtract(t, w, name=None)
tf.broadcast_to(t, [4, 4])

(4,)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[-6, -4, -2,  0],
       [-6, -4, -2,  0],
       [-6, -4, -2,  0],
       [-6, -4, -2,  0]], dtype=int32)>